rock-core/base-types

- viz/PointcloudVisualization.cpp
This patch fixed VizkitPointCloudeVisualization
> Fixed color ordering of pointcloudes

- viz/PointcloudVisualization.cpp
As requested in https://github.com/rock-core/base-types/pull/29
Unified handling of color and point arrays
> Code cleanup within PointCloudVisualization

- base/JointTransform.hpp
- base/Time.hpp
- src/Spline.cpp
- test/test.cpp
fixes separated from #22
the change in the exception can be discussed: Only changing this exception but not changing all the others which use the same style...
> Minor fixes -- dont use assert

- base/samples/RigidBodyState.hpp
see also rock-core/base-types#50
> Fix for misleading docu concerning world coordinate frame conventions

- src/Spline.cpp
- src/Spline.hpp
> Enhancements to base::Spline

- src/Spline.hpp
The method was returning wrong closest points,
as closeness was computed by distance in param space.
Also it defaulted to return a point closest to guess,
what gave wrong results in some cases : E.g:
ClosestPoints returned params [0, 0.75], were 0.75 was
exactly _pt. As guess was 0, 0 was returned.
> Fixed findOneClosestPoint method.

- base/TransformWithCovariance.hpp
Several performance improvements to TransformWithCovariance that overall improve the performance
of the TransformGraph significantly.
> TransformWithCovariance: performance improvements

- base/samples/Sonar.hpp
- fixed normalization of sonar data values in base/samples/Sonar structure
> Minor fix in base/samples/Sonar

- base/samples/Sonar.hpp
Conversions from the new sonar datatype (Sonar) to the legacy ones (SonarBeam and SonarScan).
> Sonar datatype conversions

- base/TimeMark.hpp
Also, include its streaming operator into base namespace
> Make TimeMark const correct

- src/logging/logging_iostream_style.h
- src/logging/logging_printf_style.cpp
- src/logging/logging_printf_style.h
nothing special, just strolling by...
> Minor improvements in logging

- base/samples/DepthMap.hpp
- base/samples/Pointcloud.hpp
- viz/DepthMapVisualization.cpp
- viz/DepthMapVisualization.hpp
Furthermore, make it possible to combine colorization and remission visualization.
Also, fixed some typos.
> Make it possible to change the default color of DepthMap visualization.

- base/commands/Motion2D.hpp
- viz/RigidBodyStateVisualization.cpp
- viz/RigidBodyStateVisualization.hpp
- viz/vizkit_plugin.rb
To support omnidirectional drives I suggest adding a heading value to Motion2D-command.
(As suggested in comment of previous committer)
> Added heading to Motioncommand2d

- src/samples/DepthMap.hpp
- test/test.cpp
Thanks @Rauldg for reporting this issue.
It also add missing unit test for this case.
> DepthMap: fixed an issue when computing the step resolution in the polar case

- src/samples/DistanceImage.cpp
- test/test.cpp
the conversion from DistanceImage to PointCloud was creating PointClouds of uninitialized points.
> src: DistanceImage fix getPointCloud method

- src/Angle.hpp
add less than or equal (<=) and greater than or equal (>=)
> two new comparison operators to base/Angle

- viz/TrajectoryVisualization.cpp
- proper variable initialization in constructor
- c++11 code was removed
- old points are removed again when addSpline is used
- removed debug outprints
- fixed use of wrong variable and qt property name
> TrajectoryVisualization: fixed severally issues that have been recently introduced

- src/samples/DistanceImage.cpp
- src/samples/DistanceImage.hpp
- viz/PluginLoader.cpp
- viz/vizkit_plugin.rb
also fixed parameter type in setSize method
> added missing DistanceImage vizkit plugin export

- viz/RigidBodyStateVisualization.cpp
- viz/RigidBodyStateVisualization.hpp
- viz/vizkit_plugin.rb
Adds the ability to visualize TransformWithCovariance to the RigidBodyState Visualization
> Add basic TransformWithCovariance viz by using the RBS Viz

- src/Time.cpp
- src/Time.hpp
- test/test.cpp
returns the time as a std::vector<int> containing
microseconds, milliseconds, seconds, minutes, hours and days
in that order.
> Added toTimeValues to base::time

- CMakeLists.txt
- test/viz/helpers.rb
- test/viz/test_trajectory_visualization.rb
- viz/TrajectoryVisualization.cpp
- viz/TrajectoryVisualization.hpp
There's a few things that are gained, namely the possibility to explicitly pass sampling parameters.
> viz: expose method to add spline in TrajectoryVisualization

- test/CMakeLists.txt
- test/test_DepthMapVisualization.cpp
- viz/DepthMapVisualization.cpp
- viz/DepthMapVisualization.hpp
Additionally:
* adds test program for DepthMapVisualization
* fixes crash when show_slope is selected on a DepthMap with only one row
> Allow to set size of points in DepthMapVisualization.

- src/Time.cpp
- test/test.cpp
and added additional tests to cover its occurrences
as well as some edge cases.
> Fixed an overflow issue in base::Time::toTimeValues

- src/CMakeLists.txt
- src/samples/Temperature.cpp
- src/samples/Temperature.hpp
Basically it is adding a timestamp to it.
> Create a Temperature sample.

- src/samples/RigidBodyStateSE3Vector.hpp
Filename and typename previously did not match
> Fix naming of RigidBodyStateSE3Vector

- src/CMakeLists.txt
- src/samples/Event.hpp
- src/samples/EventArray.hpp
Data types for event cameras such as [DAVIS](https://inivation.com/buy/) and [Prophesee](https://www.prophesee.ai/)
> event and event array base samples types

- src/Time.cpp
- src/Time.hpp
- test/test_Time.cpp
Meant for timeout calculations.
> add base::Time::monotonic()
