rock-core/base-types

viz/LaserScanVisualization.cpp, viz/MotionCommandVisualization.cpp, viz/PointcloudVisualization.cpp, viz/RigidBodyStateVisualization.cpp, viz/SonarGroundDistanceVisualization.hpp, viz/TrajectoryVisualization.cpp, viz/TrajectoryVisualization.hpp, viz/WaypointVisualization.cpp
In many vizkit plugins of the base types property changes are not emited. Especially when changing a plugin property in ruby the property tree in die vizkit3d GUI is not updated, if the signal is not emited. 
This commit adds the signal emit to every property setter.
=> Emit property changes

viz/RigidBodyStateVisualization.cpp, viz/RigidBodyStateVisualization.hpp
This adds texturing and bump-mapping support to the RBS visualizer. Since the visualizer already supports loading models, I felt it was the best place right now.
=> Viz add texturing support to rbs visualization

bindings/ruby/ext/base_types_ruby/Eigen.cpp
The methods were returning a int instead a unsinged int. This fixes compiler warnings in base/orogen/std. The Eigen methods return unsigned ints already.
=> ruby: fix signed-ness of size-related methods in Eigenn bindings

bindings/ruby/lib/base/geometry/spline.rb, bindings/ruby/lib/base/typelib/spline.rb, bindings/ruby/lib/base/typelib_plugin.rb
It is incompatible with the new registry export mechanism in
Typelib's ruby bindings.
=> remove base/geometry/spline

base/Angle.hpp, base/Pose.hpp, base/Time.hpp, base/Waypoint.hpp, base/samples/Frame.hpp, base/samples/RigidBodyState.hpp
Some simple fixes which accumulated while playing around. The most controversial would be dcc0bb005e1ca20253c437dd16709327eb60d339
In 61b4abdefcfe24c6e39277789bfef46a7797d0a3 the default constructor still does zero-initialization -- instead of NaN as discussed on the ML.
=> Fix shadow warnings

base/Angle.hpp, base/Pressure.hpp, base/Temperature.hpp
This is to prevent accidental use of uninitialized values.
=> Initialize Angle, Pressure and Temperature with base::unknown in default constructor

base/samples/DepthMap.hpp
This time field is picked up by the stream aligner and transformer.
I noticed that this is missing for this type, when I was reviewing the new sonar type.
IMO the more cleaner option would be to inherit every type in samples from a timestamp interface, which implements a getTimestamp method the transformer could use.
=> DepthMap: added an additional single time field

bindings/ruby/lib/base/typelib/eigen.rb
The randomly-initialized default value was not consistent w.r.t.
the size of the vector, and would sometimes lead to bad allocation
exceptions being thrown when converting to Eigen::MatrixX
=> ruby: fix default value of wrappers/MatrixX

viz/RigidBodyStateVisualization.cpp, viz/RigidBodyStateVisualization.hpp
This is useful when visualizing multiple frames in the same visualization.
To activate this, setTextSize to a positive value.
Warning: If the name of the sourceFrame changes, the visualization is not automatically updated. You can reset the size to do so.
=> Optionally show the source frame of a RigidBodyState

viz/TrajectoryVisualization.cpp
If the line width is set before the plugin is displayed the geode is not present.
=> viz: fix segfault in case of setting line width

base/samples/DepthMap.hpp, test/test.cpp
This fixes the issue that this particular conversion method couldn't be used with floating point transformations.
=> fixed non templated quaternions in depth map conversion method

viz/DepthMapVisualization.cpp
Accuracy is not really critical in this case, but it is also easier to see what is calculated.
=> Replace acos computation by equivalent (and more accurate) atan2 

base/Eigen.hpp, test/CMakeLists.txt, test/test_Eigen.cpp
The previous implementation was essentially a No-Op, because singular values are always non-negative by definition.
I don't know if this method was actually used somewhere, as it is unlikely to have made a difference ...
=> Let guaranteeSPD actually return a symmetric positive definite matrix.

base/commands/LinearAngular6DCommand.hpp
@saarnold @doudou 
I've moved `LinearAngular6DCommand` from auv_control to base/types, since previously many other components had to depend on auv_control only to have access to this specific type.
I put the type into `base/commands` namespace and created a typedef inside `base` to guarantee backwards compatibility.
=> Move LinearAngular6DCommand from auv_control

src/samples/DepthMap.hpp, test/test.cpp, viz/DepthMapVisualization.hpp
Fix for several instances of an Eigen alignment exception:
test-range: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:86: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array() [with T = double; int Size = 4; int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.
In DepthMap.hpp: using Eigen::aligned_allocator in the declarations of std::vector containing Eigen vectors or matrices.
In DepthMapVisualization.hpp: adding the Eigen macro for the declaration of classes with Eigen vector/matrix members.
=> Fix of Eigen alignment exceptions with Depth Map

src/JointLimitRange.cpp, src/Time.cpp, src/Time.hpp, src/Timeout.cpp, test/CMakeLists.txt, test/test.cpp, test/test_Timeout.cpp
When timeout is initialized with a null time, it is considered to be a maximum timeout. So timeleft should return a maximum value instead of zero.
Besides, the initilization fromMicroseconds and fromMiliseconds in base::Time was unsigned and the internal storage from time is signed. To be consistent with the documentation and with the expected behaviour of Timeout::timeleft() (return negative time after timeout is elapsed), the arguments from these methods were also changed.
Added also unit tests to cover this changes
=> Changes in the behaviour of Timeout::timeLeft() to be consistent with documentation

src/samples/RigidBodyAcceleration.cpp, src/samples/RigidBodyAcceleration.hpp
There is no angular acceleration type for a rigid body, so I added it into this type.
Signed-off-by: Alex Fernandes Neves <alexfneves@gmail.com>
=> Adding angular accelration to the rigid body acceleration type

src/samples/DistanceImage.cpp, src/samples/DistanceImage.hpp, test/test.cpp
Also:
- forward time stamp to point cloud
- fixed indentation to be consistent
- extended unit tests
=> DistanceImage: compute the scene point after sanity checks

bindings/ruby/lib/base/typelib/rigid_body_state.rb
Just to avoid generating huge amounts of objects just to create
an invalid RBS
=> ruby: create a RBS.invalid value only once and dup it

src/CMakeLists.txt, src/samples/PoseWithCovariance.cpp, src/samples/PoseWithCovariance.hpp, test/test.cpp
This type shall be used in the future to express transformations.
I know that replacing the RigidBodyState will be a very long (and hard) process and I don't plan to force anyone to use this type. The idea is to first integrate this type in the back-end of the transformer while keeping the interfaces to the RigidBodyState and also add interfaces for the new type. At that point users could at least use the new type inside of their tasks and libraries already.
In contrast to the RigidBodyState this type has a full pose covariance matrix, no velocity members and a hopefully more intuitive frame naming.
=> New transformation type

src/samples/RigidBodyAcceleration.cpp, src/samples/RigidBodyAcceleration.hpp
I'm trying to not repeat the fiasco of the convention for velocities in RBS (see #99 and #100).
The original documentation stated that the frame of reference should be the world frame, but
within the discussion about RBS, people started (rightly) pointing out reasons why the body
frame would make more sense.
So, change the documentation of the type to match this idea. RBA is not widely used, and is
relatively new (when compared to RBS), so I hope this change will be accepted.
=> clarify RigidBodyAcceleration's usage

src/samples/RigidBodyState.hpp
As the frames are formally described as sourceFrame and targetFrame,
make it clear that the angular velocity is represented in sourceFrame.
Let an indication that it is the "body" frame, as in the RigidBodyState documentation
=> Make explicit that body fixed frame is the sourceFrame

bindings/ruby/lib/sisl/spline.rb
This is potentially a very expensive operation (in my case,
was not done after 30s+ which is really bad in the default
pretty-printing function (i.e. can block exception display)
=> ruby: do not display the curve length while pretty-printing SISL::Spline

CMakeLists.txt, viz/CMakeLists.txt
qt4 is an optional requirement only needed for the optional viz part of the package.
Moving it into the viz directory fixes building on systems, which don't have qt4 installed.
=> Fix building without qt4

CMakeLists.txt, bindings/ruby/CMakeLists.txt, src/CMakeLists.txt, src/base-types-sisl.pc.in, test/CMakeLists.txt, viz/CMakeLists.txt
@saarnold 
should be applied in combination with: rock-core/tools-service_discovery#9
base-orogen-types also requires adaption which is WIP: rock-core/base-orogen-types#29
=> Make SISL truely optional

src/Spline.cpp, test/test_Spline.cpp
The number of parameters must be the number of "real" points,
not just the number of points. Since the only way we could get
this number would be to scan the whole type array, just remove
the check altogether.
This fixes creating splines with parameters and derivatives
=> spline: remove wrong validity check in Spline::interpolate

src/Temperature.cpp, src/Temperature.hpp, test/CMakeLists.txt, test/test_Temperature.cpp
The boost::format was used wrongly, and therefore throwing.
=> fix ostream << Temperature

bindings/ruby/test/test_matrixx.rb, src/Angle.hpp, test/CMakeLists.txt, test/test.cpp, test/test_Angle.cpp, test/test_Time.cpp
It was not passing. base/types ... !
=> fix test suite

bindings/ruby/test/typelib/base.tlb, bindings/ruby/test/typelib/test_spline.rb
This dependency is an issue because it creates a circular dependency.
The solution of moving these files to base/orogen/types is also
problematic since the typelib conversions can be used without the
typekit (e.g. analysing pocolog logs).
Copy the current state of `base.tlb` and use it directly. Since types
aren't meant to change often, I think it provides a good middle ground.
=> remove dependency of the typelib types on the base typekit

bindings/ruby/ext/base_types_ruby/Eigen.cpp, bindings/ruby/lib/eigen.rb, bindings/ruby/test/test_matrix4.rb, bindings/ruby/test/test_matrixx.rb, bindings/ruby/test/test_vector3.rb, bindings/ruby/test/test_vectorx.rb
Two tests were not zeroing-out their matrix/vector while it was needed. Add the definition of `#zero` and `.Zero` for all types where it makes sense, and fix the tests.
=> ruby: fix spurious test failures

src/CMakeLists.txt, src/Waypoint.cpp, src/Waypoint.hpp, src/samples/BoundingBox.cpp, src/samples/BoundingBox.hpp, src/samples/OrientedBoundingBox.cpp, src/samples/OrientedBoundingBox.hpp, test/test.cpp
This PR includes two data types to represent axis-aligned and oriented bounding boxes with their uncertainty associated. These two data types could be used on object recognition applications.
=> Include BoundingBox and OrientedBoundingBox types

.gitignore, src/samples/RigidBodyState.cpp, src/samples/RigidBodyState.hpp, test/test.cpp
This PR includes methods that provides conversions between angular velocity (axis-angle representation) and the corresponding ZYX Euler angles rate (commit https://github.com/rock-core/base-types/commit/d4c075e16d70b295c3c9ae7cf37c38cfa813f215) and also takes the opportunity to perform some style changes (commit https://github.com/rock-core/base-types/commit/6e6ef43df0324e513ce753ef247d34f95cc17320) based on `rock.vscode` linter suggestions.
The Euler angles rate can be very useful in some use-cases such as for trajectory planning and control and I thought it would be a good idea to centralize this functionality directly on RBS since the Euler angles (ZYX yaw-pitch-roll convention) are well defined there. 
Reference: https://opensource.docs.anymal.com/doxygen/kindr/master/cheatsheet_latest …
=> Include Euler angles rate vector to RBS data structure

src/samples/DistanceImage.hpp
When building in Ubuntu 18.04, there is an error for the file DistanceImageVisualization.cpp:
``` [ 48%] Generating moc_DistanceImageVisualization.cxx
/usr/include/boost/predef/language/stdc.h:52: Parse error at "defined"
viz/CMakeFiles/base-viz.dir/build.make:62: recipe for target 'viz/moc_DistanceImageVisualization.cxx' failed
make[2]: *** [viz/moc_DistanceImageVisualization.cxx] Error 1
CMakeFiles/Makefile2:140: recipe for target 'viz/CMakeFiles/base-viz.dir/all' failed
make[1]: *** [viz/CMakeFiles/base-viz.dir/all] Error 2
```
This is due to an error processing a Boost include file with the Qt MOC tool (the Boost version has probably changed in Ubuntu 18.04).
To prevent that the problematic include file is processed by MOC, the include has been enclosed with:
```
#ifndef Q_MOC_RUN …
```
=> Solve issue building base/types in Ubuntu 18.04

bindings/ruby/ext/base_types_ruby/Spline.cpp
rice would generate an error when trying to get the 'vector'. I think it should work, but had other things to solve .. so I created an intermediate method does the conversion manually instead.
=> fix(ruby): return value of SplineBase#simplify

bindings/ruby/ext/base_types_ruby/Eigen.cpp
Before, x would be set to 0 even if every coeff was nan. This returns vector3d(nan, nan, nan) whenever i is nan (i.e. an Invalid quaternion).
=> fix: return vector3d(nan, nan, nan) when one of coeffs is nan

src/CMakeLists.txt, src/LogMessage.hpp
Adds a LogMessage type (a timestamped string)
Provides ability to:
* put text-based markers into binary logs, like when an experiement started 
* use a port to show/record the time of state changes
* prepeares for an (to be published) orogen plugin that copies all stdout/stderr output to an output port to be able to print all output with an application rather than searching in the text log files
=> Add Logmessage type

src/samples/Acceleration.hpp, src/samples/BodyState.hpp, src/samples/BoundingBox.hpp, src/samples/DepthMap.hpp, src/samples/DistanceImage.hpp, src/samples/Event.hpp, src/samples/EventArray.hpp, src/samples/Frame.hpp, src/samples/IMUSensors.hpp, src/samples/Joints.hpp, src/samples/LaserScan.hpp, src/samples/Pointcloud.hpp, src/samples/PoseWithCovariance.hpp, src/samples/Pressure.hpp, src/samples/RigidBodyAcceleration.hpp, src/samples/RigidBodyState.hpp, src/samples/RigidBodyStateSE3.hpp, src/samples/RigidBodyStateSE3Vector.hpp, src/samples/Sonar.hpp, src/samples/SonarBeam.hpp, src/samples/SonarScan.hpp, src/samples/Temperature.hpp, src/samples/Twist.hpp, src/samples/Wrench.hpp, src/samples/Wrenches.hpp
After this PR https://github.com/rock-core/tools-syskit/pull/452 
It is possible to signal to use the base::Time as logical time.
This PR, signals all the time fields in the base/samples that are supposed to be used as logical time when logging.
Obs: I tried to follow the same documentation style for each file... and tested that all of these styles flagas are detected.
=> chore: include meta flag for logical time in base samples

src/samples/Sonar.cpp, src/samples/Sonar.hpp, test/viz/test_sonar_visualization.rb, viz/SonarVisualization.cpp
fix: remove division by bin_count in fan segment calculus
the bin_count inside a Sonar struct is the number of bins in each beam
=> fix: use bin count getter at sonar visualization
